<?php
/**
 * Goodminton
 *
 * Copyright 2016 Goodminton AG
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * @package     Goodminton_Languager
 * @author      Pierre Bernard <pierre.bernard@foodspring.com>
 * @copyright   Copyright (c) 2016 Goodminton AG (http://goodminton.ag)
 * @license     https://opensource.org/licenses/Apache-2.0  Apache License, Version 2.0
 */

/** @var Goodminton_Languager_Block_Adminhtml_Container_Attributes_Form $this */
?>
<div id="languager_attributes">
    <table>
        <tr>
            <td><div class="content-header"><h3><?php echo Mage::helper('goodminton_languager')->__('Not translated'); ?></h3></div></td>
            <td><div class="content-header"><h3><?php echo Mage::helper('goodminton_languager')->__('Translated'); ?></h3></div></td>
        </tr>
        <tr>
            <td id="disabled">
                <ul></ul>
            </td>
            <td id="enabled">
                <ul></ul>
            </td>
        </tr>
    </table>
    <?php echo $this->getFormHtml(); ?>
</div>